import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

// Estrae il numero rata dalle note se presente all'inizio (es. "5 rata direzione lavori" -> 5)
function extractNumberFromNotes(notes) {
  const m = norm(notes).match(/^(\d+)\s*[°ªa]?\s*rata\b/i);
  return m ? parseInt(m[1], 10) : null;
}

// Rimuove il prefisso numerico "N rata" dalle note per evitare duplicazioni con "Rata N"
function stripLeadingRataNumber(notes) {
  return norm(notes).replace(/^\d+\s*[°ªa]?\s*rata\b\s*/i, '').trim();
}

// Estrae il numero rata dalla descrizione attuale del ricavo (es. "Rata 3 ...") - opzione A
function extractNumberFromDescription(description) {
  const m = norm(description).match(/\bRata\s+(\d+)\b/i);
  return m ? parseInt(m[1], 10) : null;
}

// Costruisce la descrizione nuovo formato: "Rata N · Descrizione Rata · Nome Cliente"
function buildRevenueDescription(installment, fee, revenue) {
  const parts = [];
  const numFromNotes = extractNumberFromNotes(installment?.notes);
  const numFromDesc = extractNumberFromDescription(revenue?.description);
  const rataNumber = installment?.installment_number || numFromNotes || numFromDesc;
  if (rataNumber) parts.push(`Rata ${rataNumber}`);

  // Se il numero proviene dalle note, lo rimuovo dal testo per non duplicarlo
  let notesText = installment?.notes || '';
  if (numFromNotes) notesText = stripLeadingRataNumber(notesText);
  if (notesText) parts.push(notesText);

  if (fee?.client_name) parts.push(fee.client_name);
  return parts.join(' · ') || 'Pagamento';
}

function norm(s) {
  return (s || '').replace(/\s+/g, ' ').trim();
}

// Riconosce un vecchio formato auto-generato (da rigenerare in sicurezza).
function isAutoGenerated(description, installment) {
  const d = norm(description);
  if (!d) return true;
  if (/^(pagamento|incasso)$/i.test(d)) return true;
  // Vecchi formati auto-generati noti
  if (/^Rata\b/i.test(d)) return true;
  if (/^Incasso compenso\b/i.test(d)) return true;
  return false;
}

// Trova la rata corrispondente al ricavo (approccio B):
//  - se il compenso ha 1 sola rata -> quella
//  - altrimenti match esatto per importo + data (paid_date o due_date == data ricavo)
//  - altrimenti null (incerto)
function matchInstallment(revenue, installments) {
  if (!installments || installments.length === 0) return null;
  if (installments.length === 1) return installments[0];

  const revAmount = Number(revenue.amount) || 0;
  const revDate = revenue.date;

  const exact = installments.filter((i) => {
    const amtOk = (Number(i.amount) || 0) === revAmount;
    const dateOk = i.paid_date === revDate || i.due_date === revDate;
    return amtOk && dateOk;
  });
  if (exact.length === 1) return exact[0];

  // Fallback: match per importo (1 sola rata con quell'importo)
  const byAmount = installments.filter((i) => (Number(i.amount) || 0) === revAmount);
  if (byAmount.length === 1) return byAmount[0];

  return null;
}

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

    const body = await req.json().catch(() => ({}));
    const dryRun = body?.dry_run === true;

    const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

    // Carico tutto in blocco (poche chiamate) per evitare rate limit
    const allRevenues = await base44.asServiceRole.entities.Revenue.list('-created_date', 5000);
    const revenues = allRevenues.filter((r) => r.fee_id);
    const allFees = await base44.asServiceRole.entities.Fee.list('-created_date', 5000);
    const allInstallments = await base44.asServiceRole.entities.Installment.list('-created_date', 5000);

    const feeCache = new Map(allFees.map((f) => [f.id, f]));
    const installmentsByFee = new Map();
    for (const inst of allInstallments) {
      if (!inst.fee_id) continue;
      if (!installmentsByFee.has(inst.fee_id)) installmentsByFee.set(inst.fee_id, []);
      installmentsByFee.get(inst.fee_id).push(inst);
    }

    const getFee = (id) => feeCache.get(id) || null;
    const getInstallments = (feeId) => installmentsByFee.get(feeId) || [];

    const updated = [];
    const skippedManual = [];
    const ambiguous = [];
    const errors = [];

    for (const rev of revenues) {
      try {
        const fee = getFee(rev.fee_id);
        if (!fee) {
          ambiguous.push({ revenue_id: rev.id, current: rev.description || '', reason: 'Compenso non trovato' });
          continue;
        }

        const installments = getInstallments(rev.fee_id);
        const installment = matchInstallment(rev, installments);

        // Opzione A: se non c'è rata abbinabile ma la descrizione attuale contiene "Rata N",
        // uso quel numero per ricostruire comunque la descrizione.
        if (!installment) {
          const numFromDesc = extractNumberFromDescription(rev.description);
          if (numFromDesc && isAutoGenerated(rev.description, null)) {
            const parts = [`Rata ${numFromDesc}`];
            if (fee?.client_name) parts.push(fee.client_name);
            const fallbackDescription = parts.join(' · ');
            updated.push({ revenue_id: rev.id, old: rev.description || '', new: fallbackDescription });
            if (!dryRun) {
              await base44.asServiceRole.entities.Revenue.update(rev.id, { description: fallbackDescription });
              await sleep(120);
            }
            continue;
          }
          ambiguous.push({
            revenue_id: rev.id,
            current: rev.description || '',
            reason: installments.length === 0
              ? 'Nessuna rata collegata al compenso'
              : `${installments.length} rate, impossibile abbinare con certezza (importo ${rev.amount}, data ${rev.date})`,
          });
          continue;
        }

        const newDescription = buildRevenueDescription(installment, fee, rev);
        const current = norm(rev.description);

        if (current === norm(newDescription)) continue; // già nuovo formato

        if (isAutoGenerated(rev.description, installment)) {
          updated.push({ revenue_id: rev.id, old: rev.description || '', new: newDescription });
          if (!dryRun) {
            await base44.asServiceRole.entities.Revenue.update(rev.id, { description: newDescription });
            await sleep(120);
          }
        } else {
          skippedManual.push({ revenue_id: rev.id, current: rev.description || '', suggested: newDescription });
        }
      } catch (err) {
        errors.push({ revenue_id: rev.id, error: err.message });
      }
    }

    return Response.json({
      success: true,
      dry_run: dryRun,
      total_fee_linked_revenues: revenues.length,
      updated_count: updated.length,
      skipped_manual_count: skippedManual.length,
      ambiguous_count: ambiguous.length,
      error_count: errors.length,
      updated,
      skipped_manual: skippedManual,
      ambiguous,
      errors,
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});