import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

// Costruisce la descrizione nuovo formato: "Rata N · Descrizione Rata · Nome Cliente"
function buildRevenueDescription(installment, fee) {
  const parts = [];
  if (installment?.installment_number) parts.push(`Rata ${installment.installment_number}`);
  if (installment?.notes) parts.push(installment.notes);
  if (fee?.client_name) parts.push(fee.client_name);
  return parts.join(' · ') || 'Pagamento';
}

// Normalizza per confronto (rimuove spazi multipli, trim)
function norm(s) {
  return (s || '').replace(/\s+/g, ' ').trim();
}

// Riconosce un vecchio formato auto-generato (da rigenerare in sicurezza).
// Vecchi formati noti:
//  - vuoto / "Pagamento" / "Incasso"
//  - "Rata N - <desc> <fee>" (con trattino)
//  - "Rata N · <desc> · <categoria/progetto>" (con bullet)
//  - "<desc> · <progetto/categoria> · €... · gg/mm/aaaa" (formato con importo e data)
function isAutoGenerated(description, installment) {
  const d = norm(description);
  if (!d) return true;
  if (/^(pagamento|incasso)$/i.test(d)) return true;

  const num = installment?.installment_number;
  // Inizia con "Rata N" (qualsiasi separatore) → auto-generato
  if (num && new RegExp(`^Rata\\s+${num}\\b`, 'i').test(d)) return true;
  // Inizia genericamente con "Rata <numero>"
  if (/^Rata\s+\d+\b/i.test(d)) return true;
  // Contiene un importo formattato in euro (vecchio formato con importo)
  if (/€\s?\d/.test(d) || /\d[\d.,]*\s?€/.test(d)) return true;
  // Contiene una data gg/mm/aaaa (vecchio formato con data)
  if (/\b\d{1,2}\/\d{1,2}\/\d{2,4}\b/.test(d)) return true;

  return false;
}

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

    const body = await req.json().catch(() => ({}));
    const dryRun = body?.dry_run === true;

    // Carica tutti i ricavi collegati a una rata (hanno installment_id)
    const allRevenues = await base44.asServiceRole.entities.Revenue.list('-created_date', 5000);
    const revenues = allRevenues.filter((r) => r.installment_id);

    // Cache rate e compensi
    const installmentCache = new Map();
    const feeCache = new Map();

    async function getInstallment(id) {
      if (installmentCache.has(id)) return installmentCache.get(id);
      const list = await base44.asServiceRole.entities.Installment.filter({ id });
      const inst = list?.[0] || null;
      installmentCache.set(id, inst);
      return inst;
    }
    async function getFee(id) {
      if (!id) return null;
      if (feeCache.has(id)) return feeCache.get(id);
      const list = await base44.asServiceRole.entities.Fee.filter({ id });
      const fee = list?.[0] || null;
      feeCache.set(id, fee);
      return fee;
    }

    const updated = [];
    const skippedManual = [];
    const ambiguous = [];
    const errors = [];

    for (const rev of revenues) {
      try {
        const installment = await getInstallment(rev.installment_id);
        if (!installment) {
          ambiguous.push({
            revenue_id: rev.id,
            current_description: rev.description || '',
            reason: 'Rata collegata non trovata',
          });
          continue;
        }
        const fee = await getFee(installment.fee_id || rev.fee_id);
        if (!fee) {
          ambiguous.push({
            revenue_id: rev.id,
            current_description: rev.description || '',
            reason: 'Compenso collegato non trovato',
          });
          continue;
        }

        const newDescription = buildRevenueDescription(installment, fee);
        const current = norm(rev.description);

        // Già nel nuovo formato → nessuna azione
        if (current === norm(newDescription)) continue;

        if (isAutoGenerated(rev.description, installment)) {
          updated.push({
            revenue_id: rev.id,
            old: rev.description || '',
            new: newDescription,
          });
          if (!dryRun) {
            await base44.asServiceRole.entities.Revenue.update(rev.id, { description: newDescription });
          }
        } else {
          // Descrizione manuale → non toccare, ma segnala
          skippedManual.push({
            revenue_id: rev.id,
            current_description: rev.description || '',
            suggested: newDescription,
          });
        }
      } catch (err) {
        errors.push({ revenue_id: rev.id, error: err.message });
      }
    }

    return Response.json({
      success: true,
      dry_run: dryRun,
      total_linked_revenues: revenues.length,
      updated_count: updated.length,
      skipped_manual_count: skippedManual.length,
      ambiguous_count: ambiguous.length,
      error_count: errors.length,
      updated,
      skipped_manual: skippedManual,
      ambiguous,
      errors,
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});