import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

// Estrae il numero rata dalle note se presente all'inizio (es. "5 rata direzione lavori" -> 5)
function extractNumberFromNotes(notes) {
  const m = norm(notes).match(/^(\d+)\s*[°ªa]?\s*rata\b/i);
  return m ? parseInt(m[1], 10) : null;
}

// Rimuove il prefisso numerico "N rata" dalle note per evitare duplicazioni con "Rata N"
function stripLeadingRataNumber(notes) {
  return norm(notes).replace(/^\d+\s*[°ªa]?\s*rata\b\s*/i, '').trim();
}

// Costruisce la descrizione nuovo formato: "Rata N · Descrizione Rata · Nome Cliente"
function buildRevenueDescription(installment, fee) {
  const parts = [];
  const numFromNotes = extractNumberFromNotes(installment?.notes);
  const rataNumber = installment?.installment_number || numFromNotes;
  if (rataNumber) parts.push(`Rata ${rataNumber}`);

  // Se il numero proviene dalle note, lo rimuovo dal testo per non duplicarlo
  let notesText = installment?.notes || '';
  if (numFromNotes) notesText = stripLeadingRataNumber(notesText);
  if (notesText) parts.push(notesText);

  if (fee?.client_name) parts.push(fee.client_name);
  return parts.join(' · ') || 'Pagamento';
}

function norm(s) {
  return (s || '').replace(/\s+/g, ' ').trim();
}

// Riconosce un vecchio formato auto-generato (da rigenerare in sicurezza).
function isAutoGenerated(description, installment) {
  const d = norm(description);
  if (!d) return true;
  if (/^(pagamento|incasso)$/i.test(d)) return true;
  // Vecchi formati auto-generati noti
  if (/^Rata\b/i.test(d)) return true;
  if (/^Incasso compenso\b/i.test(d)) return true;
  return false;
}

// Trova la rata corrispondente al ricavo (approccio B):
//  - se il compenso ha 1 sola rata -> quella
//  - altrimenti match esatto per importo + data (paid_date o due_date == data ricavo)
//  - altrimenti null (incerto)
function matchInstallment(revenue, installments) {
  if (!installments || installments.length === 0) return null;
  if (installments.length === 1) return installments[0];

  const revAmount = Number(revenue.amount) || 0;
  const revDate = revenue.date;

  const exact = installments.filter((i) => {
    const amtOk = (Number(i.amount) || 0) === revAmount;
    const dateOk = i.paid_date === revDate || i.due_date === revDate;
    return amtOk && dateOk;
  });
  if (exact.length === 1) return exact[0];

  // Fallback: match per importo (1 sola rata con quell'importo)
  const byAmount = installments.filter((i) => (Number(i.amount) || 0) === revAmount);
  if (byAmount.length === 1) return byAmount[0];

  return null;
}

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

    const body = await req.json().catch(() => ({}));
    const dryRun = body?.dry_run === true;

    // Tutti i ricavi collegati a un compenso
    const allRevenues = await base44.asServiceRole.entities.Revenue.list('-created_date', 5000);
    const revenues = allRevenues.filter((r) => r.fee_id);

    const feeCache = new Map();
    const installmentsByFee = new Map();

    async function getFee(id) {
      if (feeCache.has(id)) return feeCache.get(id);
      const list = await base44.asServiceRole.entities.Fee.filter({ id });
      const fee = list?.[0] || null;
      feeCache.set(id, fee);
      return fee;
    }
    async function getInstallments(feeId) {
      if (installmentsByFee.has(feeId)) return installmentsByFee.get(feeId);
      const list = await base44.asServiceRole.entities.Installment.filter({ fee_id: feeId });
      installmentsByFee.set(feeId, list || []);
      return list || [];
    }

    const updated = [];
    const skippedManual = [];
    const ambiguous = [];
    const errors = [];

    for (const rev of revenues) {
      try {
        const fee = await getFee(rev.fee_id);
        if (!fee) {
          ambiguous.push({ revenue_id: rev.id, current: rev.description || '', reason: 'Compenso non trovato' });
          continue;
        }

        const installments = await getInstallments(rev.fee_id);
        const installment = matchInstallment(rev, installments);

        if (!installment) {
          ambiguous.push({
            revenue_id: rev.id,
            current: rev.description || '',
            reason: installments.length === 0
              ? 'Nessuna rata collegata al compenso'
              : `${installments.length} rate, impossibile abbinare con certezza (importo ${rev.amount}, data ${rev.date})`,
          });
          continue;
        }

        const newDescription = buildRevenueDescription(installment, fee);
        const current = norm(rev.description);

        if (current === norm(newDescription)) continue; // già nuovo formato

        if (isAutoGenerated(rev.description, installment)) {
          updated.push({ revenue_id: rev.id, old: rev.description || '', new: newDescription });
          if (!dryRun) {
            await base44.asServiceRole.entities.Revenue.update(rev.id, { description: newDescription });
          }
        } else {
          skippedManual.push({ revenue_id: rev.id, current: rev.description || '', suggested: newDescription });
        }
      } catch (err) {
        errors.push({ revenue_id: rev.id, error: err.message });
      }
    }

    return Response.json({
      success: true,
      dry_run: dryRun,
      total_fee_linked_revenues: revenues.length,
      updated_count: updated.length,
      skipped_manual_count: skippedManual.length,
      ambiguous_count: ambiguous.length,
      error_count: errors.length,
      updated,
      skipped_manual: skippedManual,
      ambiguous,
      errors,
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});